'use strict'

const DISABLE_CRPTOGRAPHY = true
const REQUEST_ENCRYPTION_ALOGORITHM = 'aes-256-gcm'
const RESPONSE_DECRYPTION_ALOGORITHM = 'aes-256-gcm'
const API_KEY = ''
const API_ROUTES = {
  _BASE: ''
}

const DEFAULT_CONFIG = {
  DISABLE_CRPTOGRAPHY,
  REQUEST_ENCRYPTION_ALOGORITHM,
  RESPONSE_DECRYPTION_ALOGORITHM,
  API_KEY,
  API_ROUTES
}

export default DEFAULT_CONFIG
