'use strict'

const ACCESS_TOKEN_REQUEST_HEADER_KEY = 'X-ACCESS-TOKEN'
const ACCESS_TOKEN_RESPONSE_HEADER_KEY = 'X-ACCESS-TOKEN'
const SESSION_ID_REQUEST_HEADER_KEY = 'X-SESSION-ID'
const SESSION_ID_RESPONSE_HEADER_KEY = 'X-SESSION-ID'
const API_KEY_HEADER_KEY = 'X-API-KEY'
const TIMEOUT = 3000

const DEFAULT_CONSTANTS = {
  ACCESS_TOKEN_REQUEST_HEADER_KEY,
  ACCESS_TOKEN_RESPONSE_HEADER_KEY,

  SESSION_ID_REQUEST_HEADER_KEY,
  SESSION_ID_RESPONSE_HEADER_KEY,

  API_KEY_HEADER_KEY,
  TIMEOUT
}

export default DEFAULT_CONSTANTS
