export const ADD_ARTICLE = "ADD_ARTICLE";
export const SET_USER = "SET_USER";
export const GET_USER = "GET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "USERS_LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USERS_LOGIN_FAILURE";

export const LOGOUT = "USERS_LOGOUT";

export const GETALL_REQUEST = "USERS_GETALL_REQUEST";
export const GETALL_SUCCESS = "USERS_GETALL_SUCCESS";
export const GETALL_FAILURE = "USERS_GETALL_FAILURE";

export const DELETE_REQUEST = "USERS_DELETE_REQUEST";
export const DELETE_SUCCESS = "USERS_DELETE_SUCCESS";
export const DELETE_FAILURE = "USERS_DELETE_FAILUR";

export const SUCCESS = "ALERT_SUCCESS";
export const ERROR = "ALERT_ERROR";
export const CLEAR = "ALERT_CLEAR";

export const JOURNEY_ADD_REQUEST = "JOURNEY_ADD_REQUEST";
export const JOURNEY_ADD_SUCCESS = "JOURNEY_ADD_SUCCESS";
export const JOURNEY_ADD_FAILURE = "JOURNEY_ADD_FAILURE";

export const SET_LOCATION_REQUEST = "SET_LOCATION_REQUEST"
export const SET_LOCATION_SUCCESS = "SET_LOCATION_SUCCESS"
export const SET_LOCATION_FAILURE = "SET_LOCATION_FAILURE"

export const SET_SHOP_REQUEST = "SET_SHOP_REQUEST"
export const SET_SHOP_SUCCESS = "SET_SHOP_SUCCESS"
export const SET_SHOP_FAILURE = "SET_SHOP_FAILURE"

export const SET_SERVICES_REQUEST = "SET_SERVICES_REQUEST"
export const SET_SERVICES_SUCCESS = "SET_SERVICES_SUCCESS"
export const SET_SERVICES_FAILURE = "SET_SERVICES_FAILURE"

export const BOOK_APPOINTMENT_REQUEST = "BOOK_APPOINTMENT_REQUEST"
export const BOOK_APPOINTMENT_SUCCESS = "BOOK_APPOINTMENT_SUCCESS"
export const BOOK_APPOINTMENT_FAILURE = "BOOK_APPOINTMENT_FAILURE"
